### ISSUE TITLE
Add a way to disable "Previous" and "Next" buttons

### ISSUE THREAD

**Issue by boformer** [bflorat/qdwizard#3]

**Comment by bflorat** [comment]
Did you try the setCanGoPrevious() and setCanGoNext() methods of the Screen class ?

**Comment by boformer** [comment]
> package visibility in purpose so you can use them only from a Screen subclass

These methods need to be **protected** for subclass access.
No modifier means that only classes in the same package can access the classes.

**Comment by bflorat** [comment]
You're obviously right, mea culpa. We'll set these two methods protected soon. If you're in a hurry, you may call them by reflection and using setAccessible(true) in the meantime.

**Comment by boformer** [comment]
That's what I am doing.
